config/routes.rb
BlogMongodb::Application.routes.draw do
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "sessions#new"
  
  resources :sessions
  resources :users
  resources :posts

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :content, type: String
  field :author, type: String
  validates_presence_of :title, :content, :author
end

app/models/user.rb
class User
  include Mongoid::Document
  attr_accessor :password
  before_save :encrypt_password

  field :email, :type => String
  field :password_hash, :type => String
  field :password_salt, :type => String

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = User.where(:email=>email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to Post, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to log_in_path({:email => @user.email}), notice: 'user was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title= 'BlogMongodb'

    <!--[if lt IE 9]>
    = javascript_include_tag 'http://html5shim.googlecode.com/svn/trunk/html5.js'
    <![endif]-->

    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

%body
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        %a.btn.btn-navbar{ :data => { :toggle => 'collapse', :target => '.nav-collapse' } }
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

        = link_to 'MongoBlog', '#', :class=>'brand'

        .nav-collapse
          %ul.nav
            %li 
              = link_to 'View all posts', posts_path
            %li 
              = link_to 'Create post', new_post_path
            -if current_user
              %li
                =link_to 'Logged in as ' + current_user.email, '#'
              %li
                =link_to 'Log out', log_out_path
            -else
              %li 
                = link_to 'Sign up', sign_up_path
              %li 
                = link_to 'Log in', log_in_path

  .container

    -flash.each do |name, msg|
      %div{ :class => 'alert alert-block ' + ( name == :notice ? 'alert-success' : 'alert-error' ) }
        %button.close{ :type => 'button', :data => { :dismiss => 'alert' } } ×
        = msg

    .row
      .span9 
        = yield
      .span3
        %h2
          About Us
        This is a blog to practice my RoR/Bootstrap foo. There is absolutely nothing to see here, save some pretty friggin awesome RoR/Bootstrap foo! As you were.

app/views/posts/_form.html.haml
= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f|
  / .control-group
  /   = f.label :_type, :class => 'control-label'
  /   .controls
  /     = f.text_field :_type, :class => 'text_field'
  / .control-group
  /   = f.label :_id, :class => 'control-label'
  /   .controls
  /     = f.text_field :_id, :class => 'text_field'

  = f.input :title
  = f.input :content, :as => :text, :input_html => { :rows => 10 }
  = f.input :author

  / .control-group
  /   = f.label :title, :class => 'control-label'
  /   .controls
  /     = f.text_field :title, :class => 'text_field'
  / .control-group
  /   = f.label :content, :class => 'control-label'
  /   .controls
  /     = f.text_field :content, :class => 'text_field'
  / .control-group
  /   = f.label :author, :class => 'control-label'
  /   .controls
  /     = f.text_field :author, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/posts/index.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      /%th= model_class.human_attribute_name(:id)
      /%th= model_class.human_attribute_name(:_type)
      /%th= model_class.human_attribute_name(:_id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:content)
      %th= model_class.human_attribute_name(:author)
      /%th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @posts.each do |post|
      %tr
        /%td= link_to post.id, post_path(post)
        /%td= post._type
        /%td= post._id
        %td= link_to post.title, post_path(post)
        %td= post.content
        %td= post.author
        /%td=l post.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(post), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(post), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_post_path, :class => 'btn btn-primary'

app/views/posts/new.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/posts/show.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => model_class.model_name.human

/ %p
/   %strong= model_class.human_attribute_name(:_type) + ':'
/   %br
/   = @post._type
/ %p
/   %strong= model_class.human_attribute_name(:_id) + ':'
/   %br
/   = @post._id
%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @post.title
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @post.content
%p
  %strong= model_class.human_attribute_name(:author) + ':'
  %br
  = @post.author

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), posts_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(@post), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(@post), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|

  = f.input :email
  = f.input :password
  = f.input :password_confirmation

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/users/new.html.haml
- model_class = Post
.page-header
  %h1 Sign Up

= render :partial => "form"